### ISSUE TITLE
Example in readme not working.

### ISSUE THREAD

**Issue by shakyShane** [svg-sprite/gulp-svg-sprite#1]
Hi!

Your example in the readme: 

``` js
var gulp                = require('gulp'),
svgSprite               = require('gulp-svg-sprite');

gulp.src('assets/*.svg')
    .pipe(svgSprite())
    .pipe(gulp.dest('out'));
```

does not actually send any files down stream I had a quick skim through the re-written svg-sprite module and I think you'll need to specify a default config that can be extended in this gulp plugin.

If I do

``` js
gulp.src('assets/*.svg')
    .pipe(svgSprite({
        mode                : {
            css             : {     // Activate the «css» mode
                render      : {
                    css     : true  // Activate CSS output (with default options)
                }
            }
        }
    }))
    .pipe(gulp.dest('out'));
```

then everything works as expected :)

**Comment by isaaki** [comment]
Wanted to comment here on a feature of @shakyShane's plugin that I'm missing with this one: the ability to customize svg symbol ids. 

Essentially, instead of  name of  `<use xlink:href"#twitter"></use>` I'd like it to have `<use xlink:href"#icon-twitter"></use>`. And of course this `icon-` prefix should be added to each svg symbol.

The prefix option seemed like the way to do this, but in my current implementation it's only applying the prefix to the `<svg>` wrapper. 

It's possible that I'm doing something wrong. Here's what I've tried: 

```
gulp.task('makeIcons', ['copySvgIconFile'], function() {
  return gulp.src('./assets-src/icons/*.svg')
    .pipe(svgSprite({
      mode: { 
        symbol: {
          prefix: ".icon-%s",
          inline: true,
          example: true
        }
      }
    }))
    .pipe(gulp.dest('./assets-src'))
})
```

Let me know if I'm simply missing something. Otherwise, I'd love to see this feature ported over from @shakyShane's plugin.

**Comment by jkphl** [comment]
Hi @isaaki,

it's the [`shape.id.generator` option](https://github.com/jkphl/svg-sprite#a-svg-shape-configuration) you'd want to use! ;)

Pls let me know if this works for you.

Cheers,
Joschi

**Comment by isaaki** [comment]
@jkphl Sweet :) Figured I had to simply be missing something.

**Comment by jkphl** [comment]
@isaaki You're welcome! :)
